version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: projectmanagement
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "--user=root", "--password=${SPRING_DATASOURCE_PASSWORD}", "-e", "SHOW DATABASES;"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: project_tracker
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "5454:5454"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
